spring.application.name=Notes-App
spring.datasource.url=jdbc:h2:mem:notesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=${PORT:8080}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

rate.limit.capacity=10
rate.limit.refill-tokens=10
rate.limit.refill-duration-minutes=1

aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:}
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.access-key=${AWS_ACCESS_KEY_ID:}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY:}